/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
              "on-primary-fixed-variant": "#40465a",
              "secondary-fixed-dim": "#bac7de",
              "on-secondary-fixed-variant": "#3b485a",
              "tertiary-fixed-dim": "#d8c4a2",
              "on-secondary-fixed": "#0f1c2d",
              "tertiary": "#d8c4a2",
              "tertiary-container": "#1d1301",
              "surface-container": "#171f30",
              "inverse-primary": "#575e72",
              "outline-variant": "#45464c",
              "on-primary": "#293042",
              "tertiary-fixed": "#f5e0bd",
              "secondary-fixed": "#d6e3fa",
              "on-primary-fixed": "#141b2c",
              "surface-variant": "#2d3547",
              "inverse-on-surface": "#283042",
              "on-secondary-container": "#acb9cf",
              "on-error": "#690005",
              "surface-container-lowest": "#060e1e",
              "primary": "#bfc6dd",
              "on-tertiary-fixed": "#241a05",
              "background": "#0b1324",
              "surface-tint": "#bfc6dd",
              "on-surface-variant": "#c6c6cd",
              "error-container": "#93000a",
              "surface-container-highest": "#2d3547",
              "error": "#ffb4ab",
              "on-background": "#dae2fa",
              "surface": "#0b1324",
              "on-error-container": "#ffdad6",
              "primary-fixed": "#dce2fa",
              "inverse-surface": "#dae2fa",
              "on-tertiary-fixed-variant": "#52452b",
              "secondary-container": "#3d4a5c",
              "outline": "#909097",
              "surface-dim": "#0b1324",
              "primary-container": "#0d1425",
              "surface-bright": "#31394b",
              "on-tertiary": "#3b2f17",
              "secondary": "#bac7de",
              "surface-container-high": "#222a3b",
              "on-tertiary-container": "#8e7d5f",
              "on-secondary": "#243142",
              "on-primary-container": "#787e94",
              "surface-container-low": "#131b2c",
              "on-surface": "#dae2fa",
              "primary-fixed-dim": "#bfc6dd"
      },
      "borderRadius": {
              "DEFAULT": "0.125rem",
              "lg": "0.25rem",
              "xl": "0.5rem",
              "full": "0.75rem"
      },
      "spacing": {
              "margin-edge": "64px",
              "animation-curve": "cubic-bezier(0.22, 1, 0.36, 1)",
              "animation-duration-slow": "600ms",
              "unit": "8px",
              "container-max": "1440px",
              "gutter": "32px",
              "animation-duration-fast": "200ms",
              "section-gap": "160px",
              "margin-cinematic": "64px" // Added as it was used in HTML but not in config
      },
      "fontFamily": {
              "body-lg": ["Hanken Grotesk"],
              "body-md": ["Hanken Grotesk"],
              "label-caps": ["Hanken Grotesk"],
              "display-lg": ["Hanken Grotesk"],
              "headline-sm": ["Hanken Grotesk"],
              "display-xl": ["Hanken Grotesk"],
              "headline-md": ["Hanken Grotesk"]
      },
      "fontSize": {
              "body-lg": ["20px", {"lineHeight": "160%", "letterSpacing": "0.01em", "fontWeight": "400"}],
              "body-md": ["16px", {"lineHeight": "160%", "letterSpacing": "0.01em", "fontWeight": "400"}],
              "label-caps": ["12px", {"lineHeight": "100%", "letterSpacing": "0.2em", "fontWeight": "700"}],
              "display-lg": ["80px", {"lineHeight": "100%", "letterSpacing": "-0.03em", "fontWeight": "700"}],
              "headline-sm": ["32px", {"lineHeight": "120%", "letterSpacing": "-0.01em", "fontWeight": "600"}],
              "display-xl": ["120px", {"lineHeight": "110%", "letterSpacing": "-0.04em", "fontWeight": "800"}],
              "headline-md": ["48px", {"lineHeight": "110%", "letterSpacing": "-0.02em", "fontWeight": "700"}]
      }
    },
  },
  plugins: [],
}
